### PR TITLE
Runscope Live Traffic Alerts launch

### PR DESCRIPTION
**Pull request by mansilladev**

### CODE REVIEW

**Comment by kinlane** [comment]
thanks!

**Comment by mansilladev** [comment]
Something need to be updated?

**Comment by kinlane** [comment]
yeah....I will fix. up shortly...I got sidetracked doing after you postd.

**Comment by kinlane** [comment]
It was an extra <p> tag holding it up from publishing?? never seen that before. Its up! Thanks for submitting.

**Pull request merged**
